// colorSchemes.ts

export interface CustomScheme {
  name: string;
  className: string;
  variables: { [key: string]: string };
  translation: string;
}

export const colorSchemes: CustomScheme[] = [
  {
    name: '黑綠配色',
    className: 'color-scheme-black-green',
    translation: '黑綠配色',
    variables: {
      '--text-color': '#a8ff60',
      '--background-color': '#101c0b',
      '--link-color': '#4fab61',
      '--link-hover-color': '#ff6347',
      '--button-background': '#1e3321',
      '--button-hover-color': '#4fab61',
      '--button-focus-outline': '4px auto #4fab61',
      '--card-bg-color': '#e0f7fa',
    },
  },
  {
    name: '暗色模式',
    className: 'color-scheme-dark',
    translation: '暗色模式',
    variables: {
      '--text-color': '#f0f0f0',
      '--background-color': '#121212',
      '--link-color': '#ff6347',
      '--link-hover-color': '#ff4500',
      '--button-background': '#2e2e2e',
      '--button-hover-color': '#ff4500',
      '--button-focus-outline': '4px auto #ff4500',
      '--card-bg-color': '#2a2a2a',
    },
  },
  {
    name: '淺色模式',
    className: 'color-scheme-light',
    translation: '淺色模式',
    variables: {
      '--text-color': '#1a1a1a',
      '--background-color': '#ffffff',
      '--link-color': '#1e90ff',
      '--link-hover-color': '#104e8b',
      '--button-background': '#dcdcdc',
      '--button-hover-color': '#1e90ff',
      '--button-focus-outline': '4px auto #1e90ff',
      '--card-bg-color': '#f0f8ff',
    },
  },
  {
    name: '色彩豐富高對比亮色',
    className: 'color-scheme-colorful-high-contrast-bright',
    translation: '色彩豐富高對比亮色',
    variables: {
      '--text-color': '#000000',
      '--background-color': '#ffffff',
      '--link-color': '#ff0000',
      '--link-hover-color': '#ff4500',
      '--button-background': '#ffd700',
      '--button-hover-color': '#ff6347',
      '--button-focus-outline': '4px auto #ff4500',
      '--card-bg-color': '#fffacd',
    },
  },
  {
    name: '色彩豐富低對比亮色',
    className: 'color-scheme-colorful-low-contrast-bright',
    translation: '色彩豐富低對比亮色',
    variables: {
      '--text-color': '#555555',
      '--background-color': '#f0f8ff',
      '--link-color': '#87cefa',
      '--link-hover-color': '#4682b4',
      '--button-background': '#ffdab9',
      '--button-hover-color': '#87cefa',
      '--button-focus-outline': '4px auto #87cefa',
      '--card-bg-color': '#f5f5dc',
    },
  },
  {
    name: '春日櫻花',
    className: 'color-scheme-spring-sakura',
    translation: '春日櫻花',
    variables: {
      '--text-color': '#4a4a4a',
      '--background-color': '#fff0f0',
      '--link-color': '#ff758c',
      '--link-hover-color': '#ff8fa3',
      '--button-background': '#ffb3c1',
      '--button-hover-color': '#ff758c',
      '--button-focus-outline': '4px auto #ff758c',
      '--card-bg-color': '#ffe6ea',
    },
  },
  {
    name: '復古棕褐',
    className: 'color-scheme-vintage-brown',
    translation: '復古棕褐',
    variables: {
      '--text-color': '#3e2723',
      '--background-color': '#f5e6d3',
      '--link-color': '#8b4513',
      '--link-hover-color': '#a0522d',
      '--button-background': '#deb887',
      '--button-hover-color': '#8b4513',
      '--button-focus-outline': '4px auto #8b4513',
      '--card-bg-color': '#faf0e6',
    },
  },
  {
    name: '科技霓虹',
    className: 'color-scheme-tech-neon',
    translation: '科技霓虹',
    variables: {
      '--text-color': '#00ffa3',
      '--background-color': '#0b1b30',
      '--link-color': '#00bfff',
      '--link-hover-color': '#40c8ff',
      '--button-background': '#1e3050',
      '--button-hover-color': '#00ffa3',
      '--button-focus-outline': '4px auto #00ffa3',
      '--card-bg-color': '#0e253a',
    },
  },
  {
    name: '薰衣草田',
    className: 'color-scheme-lavender-field',
    translation: '薰衣草田',
    variables: {
      '--text-color': '#5e3c6a',
      '--background-color': '#f3e5f5',
      '--link-color': '#9c27b0',
      '--link-hover-color': '#ba68c8',
      '--button-background': '#e1bee7',
      '--button-hover-color': '#9c27b0',
      '--button-focus-outline': '4px auto #9c27b0',
      '--card-bg-color': '#f8f0fa',
    },
  },
  {
    name: '秋日楓葉',
    className: 'color-scheme-autumn-maple',
    translation: '秋日楓葉',
    variables: {
      '--text-color': '#4a332a',
      '--background-color': '#ffe3c6',
      '--link-color': '#d84315',
      '--link-hover-color': '#f36b2e',
      '--button-background': '#ffccbc',
      '--button-hover-color': '#d84315',
      '--button-focus-outline': '4px auto #d84315',
      '--card-bg-color': '#ffe0b2',
    },
  },
];
